---
- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Upload nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myproject
  notify: restart nginx

- name: Enable nginx configuration
  file:
    src: /etc/nginx/sites-available/myproject
    dest: /etc/nginx/sites-enabled/myproject
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true
